export const FONTS = [
  'allfonts',
  'andale',
  'arial',
  'baekmuk',
  'calibri',
  'cambria',
  'candara',
  'cjkfonts',
  'comicsans',
  'consolas',
  'constantia',
  'corbel',
  'corefonts',
  'courier',
  'droid',
  'eufonts',
  'fakechinese',
  'fakejapanese_ipamona',
  'fakejapanese',
  'fakejapanese_vlgothic',
  'fakekorean',
  'georgia',
  'impact',
  'ipamona',
  'liberation',
  'lucida',
  'meiryo',
  'opensymbol',
  'pptfonts',
  'sourcehansans',
  'tahoma',
  'takao',
  'times',
  'trebuchet',
  'uff',
  'unifont',
  'verdana',
  'vlgothic',
  'webdings',
  'wenquanyi',
  'wenquanyizenhei',
] as const;

export type FontValues = (typeof FONTS)[number];
